config/routes.rb
Rails.application.routes.draw do
  resources :busker_profiles
  resources :events
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  get '/success', to: "payments#success", as: "payment_success"
  post '/payments/webhook', to: "payments#webhook", as: "webhook"
  post '/payments', to: "payments#create_payment_intent", as: "create_payment_intent"

  get '/reviews/new/:busker_profile_id', to: 'reviews#new', as: "create_new_review"   
  post '/reviews', to: 'reviews#create'
  delete '/reviews/:id/:busker_profile_id', to: 'reviews#destroy', as: "delete_review"
  get '/reviews/:id/:busker_profile_id/edit', to: 'reviews#edit', as: "edit_review"
  patch '/reviews/:id', to: 'reviews#update'
  put '/reviews/:id', to: 'reviews#update'
  get '/reviews/:id', to: 'reviews#show', as: 'review'
end

app/models/busker_profile.rb
class BuskerProfile < ApplicationRecord
  belongs_to :user
  has_one_attached :picture
  has_many :reviews

  def self.search(query, option)
    if query 
      self.where("LOWER(#{option}) LIKE ?", "%#{query.downcase}%")
    else
      self.all
    end

  end


  #data_sanitization
  before_save :remove_whitespace

  private
  def remove_whitespace
    self.name = self.name.strip 
    self.bio = self.bio.strip
  end
  
end

app/controllers/busker_profiles_controller.rb
class BuskerProfilesController < ApplicationController
  before_action :set_busker_profile, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorise_user, only: [:edit, :update, :destroy]
  before_action :already_exist, only: [:new]

  # GET /busker_profiles or /busker_profiles.json
  def index
    @busker_profiles = BuskerProfile.search(params[:query], params[:option]).all
    @busker_profile = current_user&.busker_profile
  end

  # GET /busker_profiles/1 or /busker_profiles/1.json
  def show
    @reviews = Review.where(busker_profile_id: @busker_profile)
  end

  # GET /busker_profiles/new
  def new
    @busker_profile = BuskerProfile.new
  end

  # GET /busker_profiles/1/edit
  def edit
  end

  # POST /busker_profiles or /busker_profiles.json
  def create
    @busker_profile = current_user.build_busker_profile(busker_profile_params)

    respond_to do |format|
      if @busker_profile.save
        format.html { redirect_to @busker_profile, notice: "Busker profile was successfully created." }
        format.json { render :show, status: :created, location: @busker_profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @busker_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /busker_profiles/1 or /busker_profiles/1.json
  def update
    respond_to do |format|
      if @busker_profile.update(busker_profile_params)
        format.html { redirect_to @busker_profile, notice: "Busker profile was successfully updated." }
        format.json { render :show, status: :ok, location: @busker_profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @busker_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /busker_profiles/1 or /busker_profiles/1.json
  def destroy
    @busker_profile.destroy
    respond_to do |format|
      format.html { redirect_to busker_profiles_url, notice: "Busker profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_busker_profile
      @busker_profile = BuskerProfile.find(params[:id])
    end

    def authorise_user
      if current_user.id != @busker_profile.user_id
        flash[:error] = "you're not allowed to do that"
        redirect_to busker_profiles_path
      end
    end

    def already_exist
      if BuskerProfile.find_by_user_id(current_user.id)
        flash[:error] = "you're not allowed to do that, you've already created a profile"
        redirect_to busker_profiles_path
      end
    end

    # Only allow a list of trusted parameters through.
    def busker_profile_params
      params.require(:busker_profile).permit(:user_id, :name, :bio, :picture)
    end
end

app/helpers/busker_profiles_helper.rb
module BuskerProfilesHelper
end

app/views/busker_profiles/_form.html.erb
<%= form_with(model: busker_profile) do |form| %>
  <% if busker_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(busker_profile.errors.count, "error") %> prohibited this busker_profile from being saved:</h2>

      <ul>
        <% busker_profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :name, class:"col form-label" %>
    <%= form.text_field :name, class:"form-control", required: true %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :bio, class:"col form-label" %>
    <%= form.text_area :bio, class:"form-control", required: true %>
  </div>

   <div class="form-group mb-3">
    <%= form.label :picture, class:"col form-label" %>
    <%= form.file_field :picture, class:"form-control-file", accept: 'image/jpg, image/jpeg' %>
  </div>

  <div class="actions text-center mt-5">
    <%= form.submit class:"btn btn-info" %>
  </div>
<% end %>

app/views/busker_profiles/edit.html.erb
<div class="d-flex justify-content-center bg-secondary">
  <div class="card my-3" style="width: 60%;">
    <div class="card-body">
      <h1 class="text-center py-3">Editing Busker Profile</h1>
      <%= render 'form', busker_profile: @busker_profile %>
      <div class="text-center">
        <%= link_to 'Show', @busker_profile %> |
        <%= link_to 'Back', busker_profiles_path %>
      </div>
    </div>
  </div>
</div>

app/views/busker_profiles/index.html.erb
<div class="container">

  <p id="notice"><%= notice %></p>

  <div class="d-flex flex-column align-items-center">
    <h1 class="py-5">Busker Profiles</h1>
    <% if !@busker_profile %>  
      <div class="text-center">                          
        <%= link_to 'New Busker Profile', new_busker_profile_path, class:"btn btn-info mb-3"%>
      </div>
    <% end %>
    <div class="mb-3">
      <h4>Search</h4>
      <%=form_with url: busker_profiles_path, method: :get, local: true do |form|%>
      <%= form.label :query, "Search by:" %>
      <%= form.text_field :query %>
      <%= form.select :option, ["name", "bio"] %>
      <%= form.submit "Search" %>
      <% end %>
    </div>
  </div>


    <div class="row justify-content-center">
      <%@busker_profiles.each do |busker_profile| %>
        <div class="col col-md-4">
           <div class="card mb-3">
          <%= image_tag image_select(busker_profile), class:"card-img-top img-size" %>
            <div class="card-body">
              <h5 class="card-title"><%= busker_profile.name%></h5>
              <p class="card-text"><%= busker_profile.bio%> </p>
              <%= link_to "Details", busker_profile_path(busker_profile.id), class:"btn btn-info btn-right" %>
             
            </div>
          </div>
          
        </div> 
      <%end%>
    </div>

</div>

app/views/busker_profiles/new.html.erb
<div class="d-flex justify-content-center bg-secondary">
  <p id="notice"><%= notice %></p>
    <div class="card my-3" style="width: 60%;">
      <div class="card-body">
        <h1 class="text-center">New Busker Profile</h1>
        <%= render 'form', busker_profile: @busker_profile %>
        <div class="text-center">
          <%= link_to 'Back', busker_profiles_path %>
        </div>
      </div>
    </div>
  </div>

app/views/busker_profiles/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

    <div class="row">
      <div class="col col-md-6 mb-3">
        <div class="card">
          <%=image_tag image_select(@busker_profile), class:"thumbnail card-img top"%>
          <div class="card-body">
            <h2 class="text-center pb-3">
              <%= @busker_profile.name %>
            </h2>
            <p>
              <strong>Bio:</strong>
              <%= @busker_profile.bio %>
            </p>
            <div class ='d-flex justify-content-around'>   
              <% if current_user&.id == @busker_profile.user_id %>
                <%= link_to 'Edit', edit_busker_profile_path(@busker_profile), class: "pt-4 mr-3" %> 
                <span class="pt-4"> | </span>
                <%= link_to 'Delete', @busker_profile, method: :delete, data: {confirm: "Are you sure?"} , class: "btn pt-4 mr-3" %>
                <span class="pt-4"> | </span>
              <% end %>
              <%= link_to 'Back', busker_profiles_path, class: "btn pt-4" %>
            </div>
            <div class="text-center">
              <% if current_user&.id != @busker_profile.user_id %>
                <%= link_to 'Create a new review', create_new_review_path(@busker_profile.id), class:"btn btn-info mb-3"%>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="col col-md-6 mb-3">
        <h4 class="text-center">Reviews</h4>
        <% @reviews.each do |review| %>
          <div class="card mb-3">
            <div class="card-body">
              <figure>
                  <blockquote class="blockquote">
                      <p><%= review.comment%></p>
                      <p><%= review.rating%> stars</p>
                  </blockquote>
                  <figcaption class="blockquote-footer"><%= review.user.username%></figcaption>
              </figure>
            </div>
              
            <% if current_user&.id == review.user_id %>
              <div class ='d-flex justify-content-around'> 
                <%= link_to 'Edit', edit_review_path(review.id, @busker_profile.id), class: "btn pt-4 mr-3" %> 
                <span class="pt-4"> | </span>
                <%= link_to 'Delete', delete_review_path(review.id, @busker_profile.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn pt-4 mr-3" %>
              </div>
            <% end %>
          </div> 
        <% end %>      
      </div>
  </div>
 
</div>