config/routes.rb
Rails.application.routes.draw do
  resources :busker_profiles
  resources :events
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  get '/success', to: "payments#success", as: "payment_success"
  post '/payments/webhook', to: "payments#webhook", as: "webhook"
  post '/payments', to: "payments#create_payment_intent", as: "create_payment_intent"

  get '/reviews/new/:busker_profile_id', to: 'reviews#new', as: "create_new_review"   
  post '/reviews', to: 'reviews#create'
  delete '/reviews/:id/:busker_profile_id', to: 'reviews#destroy', as: "delete_review"
  get '/reviews/:id/:busker_profile_id/edit', to: 'reviews#edit', as: "edit_review"
  patch '/reviews/:id', to: 'reviews#update'
  put '/reviews/:id', to: 'reviews#update'
  get '/reviews/:id', to: 'reviews#show', as: 'review'
end

app/views/shared/_footer.html.erb
<div class="bg-info py-3">
  <div class="d-flex">
    <div class="ml-5">© Copyright 2021 By Celine Roure</div>
    <div class="d-flex justify-content-around">
      
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-info">
  <%= link_to "Airbusking", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav ml-auto">  
      <a href="/#about" class="nav-item nav-link">About</a>
      <%= link_to "Events", events_path, class: "nav-item nav-link" %>
      <%= link_to "Buskers profile", busker_profiles_path, class: "nav-item nav-link" %>
      <% if user_signed_in? %>
        Hi, <%= current_user.username%>, 
        <%=link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-item nav-link"%>
      <%else%>
        <%=link_to "Log in", new_user_session_path, class: "nav-item nav-link"%>
        <%=link_to "Sign Up", new_user_registration_path, class: "nav-item nav-link"%>
      <%end%>
    </div>
  </div>
</nav>