config/routes.rb
Rails.application.routes.draw do
  resources :busker_profiles
  resources :events
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  get '/success', to: "payments#success", as: "payment_success"
  post '/payments/webhook', to: "payments#webhook", as: "webhook"
  post '/payments', to: "payments#create_payment_intent", as: "create_payment_intent"

  get '/reviews/new/:busker_profile_id', to: 'reviews#new', as: "create_new_review"   
  post '/reviews', to: 'reviews#create'
  delete '/reviews/:id/:busker_profile_id', to: 'reviews#destroy', as: "delete_review"
  get '/reviews/:id/:busker_profile_id/edit', to: 'reviews#edit', as: "edit_review"
  patch '/reviews/:id', to: 'reviews#update'
  put '/reviews/:id', to: 'reviews#update'
  get '/reviews/:id', to: 'reviews#show', as: 'review'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  has_one_attached :picture

  def self.search(query, option)
    if query && option
      self.where("LOWER(#{option}) LIKE ?","%#{query.downcase}%")
    else
      self.all
    end
  end


  #data_sanitization
  before_save :remove_whitespace
  before_validation :convert_price_to_cents, if: :price_changed?


  private
  def remove_whitespace
    self.title = self.title.strip 
    self.description = self.description.strip
  end

  def convert_price_to_cents
    self.price = (self.attributes_before_type_cast["price"].to_f * 100).round
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorise_user, only: [:edit, :update, :destroy]
  before_action :busker_only, only: [:new]
  before_action :set_genres, only: [:new, :edit, :update]

  # GET /events or /events.json
  def index
    @events = Event.search(params[:query], params[:option]).all.includes(:genre)
    @busker_profile = current_user&.busker_profile
  end

  # GET /events/1 or /events/1.json
  def show
    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'], 
      customer_email: current_user&.email,
      line_items: [{
        name: @event.title, 
        description: @event.description, 
        amount: @event.price,
        currency: 'aud' ,
        quantity: 100
      }], 
      payment_intent_data: {
        metadata: {
          user_id: current_user&.id,
          listing_id: @event.id
        }
      }, 
      success_url: "#{root_url}/success?title=#{@event.title}", 
      cancel_url: "#{root_url}/events"
    )

    @session_id = session.id 
    @busker_profile = BuskerProfile.all.find_by_user_id(@event.user_id)
  end
  

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = current_user.events.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    def authorise_user
      if current_user.id != @event.user_id
        flash[:error] = "you're not allowed to do that"
        redirect_to events_path
      end
    end

    def busker_only
      if !current_user.busker_profile
        flash[:error] = "You're not allowed to do that, first create a busker profile"
        redirect_to events_path
      end
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:user_id, :genre_id, :title, :description, :date, :time, :price, :quantity, :picture)
    end

    def set_genres
      @genres = Genre.all
    end

end

app/helpers/events_helper.rb
module EventsHelper
  def image_select(event)
    if event.picture.attached?
      return event.picture 
    else
      return "default.jpg"
    end
  end
end

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="form-group mb-3">
    <%= form.label :title, class:"col form-label" %>
    <%= form.text_field :title, class:"form-control", required: true %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :genre_id, class:"col form-label" %>
    <%= form.select :genre_id, @genres.map {|g| [g.name, g.id]}, class: "form-select" %>
  </div>


  <div class="form-group mb-3">
    <%= form.label :description, class:"col form-label" %>
    <%= form.text_area :description, class:"form-control", required: true %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :date, class:"col form-label" %>
    <%= form.date_field :date %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :time, class:"col form-label" %>
    <%= form.time_select :time %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :price, class:"col form-label" %>
    <%= form.number_field :price, step: "0.01" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :quantity, class:"col form-label" %>
    <%= form.number_field :quantity, step: "1" %>
  </div>

   <div class="form-group mb-3">
    <%= form.label :picture, class:"col form-label" %>
    <%= form.file_field :picture, class:"form-control-file", accept: 'image/jpg, image/jpeg' %>
  </div>

  <div class="actions text-center mt-5">
    <%= form.submit class:"btn btn-info"%>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="d-flex justify-content-center bg-secondary">
  <div class="card my-3" style="width: 60%;">
    <div class="card-body">
      <h1 class="text-center">Editing Event</h1>
      <%= render 'form', event: @event %>
      <div class="text-center">
        <%= link_to 'Show', @event %> |
        <%= link_to 'Back', events_path %>
      </div>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="d-flex flex-column align-items-center">
    <h1 class="py-5">Events</h1>
     <div class="text-center">
      <% if !current_user %>
        <%=button_to "Login to create an event", new_user_session_path, class: "btn btn-info"%>
      <% elsif @busker_profile %>
        <%= link_to 'New Event', new_event_path, class:"btn btn-info mb-3"%>
      <%else%>
        <%= link_to 'Create a busker profile first', new_busker_profile_path, class:"btn btn-info mb-3"%>
      <%end%>
    </div>

    <div class="py-4">
      <h4>Search</h4>
      <%=form_with url: events_path, method: :get, local: true do |form|%>
        <%= form.label :query, "Search by:"%>
        <%=form.text_field :query%>
        <%=form.select :option, ["title", "description"]%>
        <%=form.submit "Search"%>
      <%end%>
    </div>
  </div>

  <div class="row justify-content-center">
    <%@events.each do |event| %>
        <div class="col col-md-4">
        <div class="card mb-3">
          <%= image_tag image_select(event), class:"card-img-top img-size" %>
          <div class="card-body">
            <h5 class="card-title"><%= event.title%></h5>
            <p class="card-text"><%= event.description%></p>
            <p class="card-text"><%= event.date%></p>
            <p class="card-text">$<%= (event.price / 100.00) %></p>
            <%= link_to "Details", event_path(event.id), class:"btn btn-info btn-right" %>
          </div>
        </div>
      </div> 
    <%end%>
  </div>
</div>

app/views/events/new.html.erb
<div class="d-flex justify-content-center bg-secondary">
  <div class="card my-3" style="width: 60%;">
    <div class="card-body">
      <h1 class="text-center">New Event</h1>
      <%= render 'form', event: @event %>
      <div class="text-center">
        <%= link_to 'Back', events_path %>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="d-flex flex-column flex-md-row my-2 my-md-5">
    <div class="content col-12 col-md-7 col-lg-8 p-0 pr-md-3">
      <div class="col-12 p-0 main-preview mb-4">
        <%=image_tag image_select(@event), class:"thumbnail card-img top"%>
      </div>
    </div>

    <div class="sidebar col-lg-4 p-0 mx-2 d-md-block">
      <h1 class="mb-sm-2 mb-md-5"><%=@event.title%></h1>
      <h2 class="mb-sm-2 mb-md-5"><%= link_to @busker_profile.name, busker_profile_path(@busker_profile.id)%> </h2>
      <h4 class="text-muted pb-sm-2 pb-md-3">Date: <%=@event.date.to_time.strftime("%A, %d %b %Y")%></h4>
      <h4 class="text-muted pb-sm-2 pb-md-3">Time: <%=@event.time.to_time.strftime("%H:%M %p")%></h4>
      <h4 class="text-muted pb-sm-2 pb-md-3">Tickets left: <%= @event.quantity %> </h4>
      <p class="blockquote mt-2"><%=@event.description%></p>

      <% if current_user && @event.sold == false %>
        <%= button_to "Buy: $#{@event.price / 100.00}", create_payment_intent_path, method: :post, remote: true, params:{id: @event.id}, class: "btn btn-primary p-3 text-center"%>
      <% elsif @event.sold == true %>
        <button class='btn btn-secondary' disabled>SOLD OUT</button>
      <%else%>
        <%=button_to "Login to buy", new_user_session_path, class: "btn btn-info"%>
      <%end%>
  
      <div class ='d-flex justify-content-around'>   
        <% if current_user&.id == @event.user_id %>
          <%= link_to 'Edit', edit_event_path(@event.id), class: "btn pt-4 mr-3" %> 
          <span class="pt-4"> | </span>
          <%= link_to 'Delete', @event, method: :delete, data: {confirm: "Are you sure?"}, class: "btn pt-4 mr-3" %>
          <span class="pt-4"> | </span>
        <% end %>
        <%= link_to 'Back', events_path, class: "btn pt-4" %>
      </div>
    </div>
    </div>

</div>
      

  